config: &config
    working_directory: /go/src/github.com/turtledev/circle-me
    docker:
        - image: circleci/golang:1.8

version: 2
jobs:
    test:
        <<: *config
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run: dep ensure
            - run: make test

    build:
        <<: *config
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run: dep ensure
            - run: make
            - persist_to_workspace:
                root: .
                paths: 
                    - circle-me
    deploy:
        <<: *config
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: sudo apt-get install awscli git
            - run: aws configure set default.s3.signature_version s3v4
            - run: |
                set -x
                base=dist
                out=$base/circle-me

                if [[ ! -z "${CIRCLE_TAG}" ]]; then
                    out="$out/${CIRCLE_TAG}"
                else
                    out="$out/master"
                fi
                
                rm -rf $out
                mkdir -p $out
                cp circle-me $out

                if [[ "${CIRCLE_BRANCH}" == master || $(git branch --contains "${CIRCLE_TAG}" | sed "s/(.*)//" | tr -d " *") == master ]]; then
                    aws s3 sync $base s3://binaries-circle
                else
                    echo "Deploys only work for"
                    echo "    * master branch"
                    echo "    * tags"
                    echo "nothing to do here"
                fi

workflows:
    version: 2
    
    # runs for every commit, on any branch (except master)
    run-tests:
        jobs:
            - test:
                filters:
                    branches:
                        ignore: master
                

    # run for only master
    build-and-deploy-latest:
        jobs:
            - test:
                filters:
                    branches:
                        only: master
            - build:
                requires:
                    - test
            - deploy:
                requires:
                    - build

    # tag specific
    build-and-deploy-release:
        jobs:
            - test:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/

            - build:
                requires:
                    - test
                filters:
                    tags:
                        only: /.*/
            - deploy:
                requires:
                    - build
                filters:
                    tags:
                        only: /.*/

