version: 2
jobs:
    test:
        docker:
            - image: circleci/golang:1.8
        working_directory: /go/src/github.com/turtledev/circle-me
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run: dep ensure
            - run: make test

    build_executable:
        docker:
            - image: circleci/golang:1.8
        working_directory: /go/src/github.com/turtledev/circle-me
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run: dep ensure
            - run: make
            - store_artifacts:
                path: circle-me


workflows:
    version: 2
    
    # runs for every commit, on any branch (except master)
    test-workflow:
        jobs:
            - test:
                filters:
                    branches:
                        ignore: master
                

    # run for only master
    build-and-deploy-master:
        jobs:
            - test:
                filters:
                    branches:
                        only: master
            - build_executable:
                requires:
                    - test

    # run on master, for every tag
    build-and-deploy-tag:
        jobs:
            - test:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/

            - build_executable:
                requires:
                    - test
                filters:
                    tags:
                        only: /.*/

