config: &config
    working_directory: /go/src/github.com/turtledev/circle-me
    docker:
        - image: circleci/golang:1.8

version: 2
jobs:
    test:
        <<: *config
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run: dep ensure
            - run: make test

    build:
        <<: *config
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run: dep ensure
            - run: make
            - persist_to_workspace:
                root: .
                paths: 
                    - circle-me
    deploy:
        <<: *config
        steps:
            - attach_workspace:
                at: .
            - run: sudo apt-get install awscli
            - run: |
                if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
                    aws s3 sync circle-me s3://testbucketforme1337/circle-me/master/
                else
                    echo "not on branch master; not deploying"
                fi

workflows:
    version: 2
    
    # runs for every commit, on any branch (except master)
    test-workflow:
        jobs:
            - test:
                filters:
                    branches:
                        ignore: master
                

    # run for only master
    build-and-deploy-master:
        jobs:
            - test:
                filters:
                    branches:
                        only: master
            - build:
                requires:
                    - test
            - deploy:
                requires:
                    - build

    # run on master, for every tag
    # build-and-deploy-tag:
    #     jobs:
    #         - test:
    #             filters:
    #                 branches:
    #                     ignore: /.*/
    #                 tags:
    #                     only: /.*/

    #         - build_executable:
    #             requires:
    #                 - test
    #             filters:
    #                 tags:
    #                     only: /.*/

